// Tests the distribution generated by Java's Math.random() function.
public class TestRandom {
	public static void main(String[] args) {

		int Counter = Integer.parseInt(args[0]);

		int countGreater = 0; // לכמה פעמים המספר גדול מ-0.5
		int countSmaller = 0; // לכמה פעמים המספר קטן או שווה ל-0.5

		for (int i = 0; i < Counter; i++) {
			double randomNum = Math.random(); // מגריל מספר

			if (randomNum > 0.5) {
				countGreater++;
			} else {
				countSmaller++;
			}

		}

		
		System.out.println("> 0.5: " + countGreater + " times");
        System.out.println("<= 0.5: " + countSmaller + " times");

		System.out.print("Ratio: ");

		if (countSmaller != 0){

			double Ratio = (double)countGreater / countSmaller;
			System.out.println(Ratio);
		}

		else {
			
		}
		
		}

	}

